POST https://node-api-fastify-s45a.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Primeiro video",
    "duration": 180
}

###

GET https://node-api-fastify-s45a.onrender.com/videos?search=teste

###

PUT https://node-api-fastify-s45a.onrender.com/videos/40879c45-aedc-4c9c-8cc2-eb874b1c2c73
Content-Type: application/json

{
    "title": "Video teste ATUALIZACAO",
    "description": "ATUALIZACAO OK",
    "duration": 180
}

###

DELETE https://node-api-fastify-s45a.onrender.com/videos/40879c45-aedc-4c9c-8cc2-eb874b1c2c73